version: "2"
services:
  database:
    image: mongo:4.4
    container_name: database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=adminPHQ9
      - MONGO_INITDB_DATABASE=phq9_database
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=adminPHQ9
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
    networks:
      - 'phq9-network'

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminPHQ9
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: "27017"
      VIRTUAL_HOST: database.phq9-thesis.page
      LETSENCRYPT_HOST: database.phq9-thesis.page
      VIRUTAL_PORT: 8081
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - phq9-network
    depends_on:
      - database

  server:
    container_name: phq9-backend
    image: "phuicmt/phq-9-backendv2"
    restart: always
    networks:
      - phq9-network
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - database
    volumes:
      - videos_storage:/server/app/videos_storage
      - images_storage:/server/app/images_storage

  web:
    container_name: phq9-fontend
    image: "phuicmt/phq-9-fontendv2"
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server
      - database
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
      VIRTUAL_HOST: phq9-thesis.page
      LETSENCRYPT_HOST: phq9-thesis.page
    network_mode: bridge
    # networks:
    #   - phq9-network

  nginx-proxy:
      image: nginxproxy/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - conf:/etc/nginx/conf.d
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
      network_mode: bridge
      links:
        - web

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-lets
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    depends_on:
      - nginx-proxy
    # networks:
    #   - phq9-network

  portainer_agent:
    image: portainer/agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    networks:
      - phq9-network

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      VIRTUAL_HOST: portainer.phq9-thesis.page
      LETSENCRYPT_HOST: portainer.phq9-thesis.page
      VIRTUAL_PORT: 9000
    networks:
      - phq9-network

networks:
  phq9-network:
    driver: bridge

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  dhparam:
  portainer_data:
  videos_storage:
  images_storage: